# SPDX-License-Identifier: Apache-2.0

name: "Pull Request Labeler"

on:
- pull_request_target

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: "Harden Runner"
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: "Labeler Action"
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false
